#!/bin/bash -e

# Start snort
/usr/local/bin/snort -g snort -u snort -c /etc/snort/snort.conf -D

# Start barnyard
/usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf \
	-G /etc/snort/gen-msg.map \
	-S /etc/sid-msg.map \
	-d /var/log/snort \
	-f snort.u2 \
	-w /var/log/snort/barnyard2.waldo \
	-D 


