#!/bin/bash -e

# Start snort
/usr/local/bin/snort -g snort -u snort -c /etc/snort/snort.conf -i eth0 -D 

# Start barnyard
/usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf \
	-d /var/log/snort \
	-f snort.u2 \
	-D 


